# docker-compose for SFTP server
version: '3.2'
services:
  sftp: # https://hub.docker.com/r/atmoz/sftp
    image: atmoz/sftp
    volumes:
      - /home/david/.ssh/sftp_org_rsa.pub:/home/foo/.ssh/keys/id_rsa.pub:ro
      - /home/david/upload:/home/foo/upload"
    ports:
      - '2222:22'
      # user:pass[:e]{:uid[:gid[:dir1[,dir2]...]]]
    command: foo:pass:::upload
    
  activemq: # https://hub.docker.com/r/webcenter/activemq
    image: 'webcenter/activemq:5.14.3'
    environment:
      ACTIVEMQ_ADMIN_LOGIN:    'mqAdmin'
      ACTIVEMQ_ADMIN_PASSWORD: 'mqAdmin123'
    ports:
      - '61613:61613'
      - '61616:61616'
      - '8161:8161'
